### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by danedavid** [martianyi/github-sloc#1]
![image](https://user-images.githubusercontent.com/19928280/30377525-a3b51652-98ad-11e7-9861-4bffb52b66b0.png)

The extension is not working always

**Comment by martianyi** [comment]
The server returns a 403 error, maybe because you exceed the api rate limit, if you haven't set your personal token, try creating and setting one and see if it works.

**Comment by danedavid** [comment]
Ya.. that resolved it! Thanks!
